name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t JVS-CRUD-CICD .

      - name: Transfer files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ec2-52-221-184-201.ap-southeast-1.compute.amazonaws.com
          username: ikon
          password: 12345678
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/ikon/JVS-CRUD-CICD"

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ec2-52-221-184-201.ap-southeast-1.compute.amazonaws.com
          username: ikon
          password: 12345678
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ikon/JVS-CRUD-CICD
            docker stop JVS-CRUD-CICD || true
            docker rm JVS-CRUD-CICD || true
            docker run -d -p 80:5000 --name JVS-CRUD-CICD JVS-CRUD-CICD
