name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_INSTANCE_HOST }}
          username: ${{ secrets.EC2_INSTANCE_NAME }}
          password: ${{ secrets.EC2_INSTANCE_PASSWORD }}
          script: |
            cd /home/ikon/JVS-CRUD-CICD
            git pull
            docker build -t jvs-crud-cicd:v1 .
            docker stop jvs-crud-cicd
            docker rm jvs-crud-cicd
            docker run -d -p 80:5000 --name jvs-crud-cicd jvs-crud-cicd:v1
