name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ec2-52-221-184-201.ap-southeast-1.compute.amazonaws.com
          username: ikon
          password: 12345678
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ikon/JVS-CRUD-CICD
            docker build -t jvs-crud-cicd:v1 .
            docker stop jvs-crud-cicd:v1
            docker rm jvs-crud-cicd:v1
            docker run -d -p 80:5000 --name jvs-crud-cicd jvs-crud-cicd:v1
